name: Issue
description: Report a bug or request a feature
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug or feature you'd like
      placeholder: A clear description of what you're experiencing or requesting
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature Request
        - Question
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce (for bugs)
      description: How can we reproduce this issue?
      placeholder: |
        1. Create a template with...
        2. Run `pdfn dev`...
        3. See error...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of pdfn are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: false
